### PR TITLE
Allow loading links from other apps

### PR DESCRIPTION
**Pull request by TheDorkKnightRises**
See issue #3 (no idea why it was closed, it didn't look like it was fixed)

Clicking a link in a different app and opening in Colombo would lead to a blank browser page. This change should fix that.

### CODE REVIEW

**Comment by RiccardoBusetti** [comment]
Wait i am changing a lot of the project structure, so for avoid conflicts i will include your code my self

**Comment by RiccardoBusetti** [comment]
Is already working :/

**Comment by TheDorkKnightRises** [comment]
Yeah, it wasn't working when I pushed the fix :stuck_out_tongue_closed_eyes: 
The Intent wasn't being handled.

**Comment by RiccardoBusetti** [comment]
Oh OK, btw thanks

**Pull request closed without merging**
